sudo: required
services:
    - docker

before_install:
    - docker build -t doodee24/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true doodee24/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-1"
    app: "docker-react"
    evn: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-397521309337"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"